runtime: nodejs20
env: standard

entrypoint: node server.mjs

handlers:
- url: /.*
  script: auto

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic

